### ISSUE TITLE
[BUG] doc[field] == null causing error in CSV report

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

---
## Version
Opendistro Elasticsearch 1.13.0 standalone linux
Opendistro Kibana 1.13.0 standalone linux

## Error description
If the saved discover table includes a null value the csv export will fail with the error message:
```
[08:16:09.781] [error][opendistroReportsKibana][plugins] Failed to generate report: TypeError: Cannot read property 'toString' of null
  log   [08:16:09.782] [error][opendistroReportsKibana][plugins] TypeError: Cannot read property 'toString' of null
    at sanitize (/srv/opendistroforelasticsearch-kibana/plugins/opendistroReportsKibana/server/routes/utils/dataReportHelpers.ts:227:18)
    at getEsData (/srv/opendistroforelasticsearch-kibana/plugins/opendistroReportsKibana/server/routes/utils/dataReportHelpers.ts:172:34)
    at convertEsDataToCsv (/srv/opendistroforelasticsearch-kibana/plugins/opendistroReportsKibana/server/routes/utils/savedSearchReportHelper.ts:266:18)
    at generateReportData (/srv/opendistroforelasticsearch-kibana/plugins/opendistroReportsKibana/server/routes/utils/savedSearchReportHelper.ts:151:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 error  [08:16:07.104]  Error: Internal Server Error
    at HapiResponseAdapter.toError (/srv/opendistroforelasticsearch-kibana/src/core/server/http/router/response_adapter.js:132:19)
    at HapiResponseAdapter.toHapiResponse (/srv/opendistroforelasticsearch-kibana/src/core/server/http/router/response_adapter.js:86:19)
    at HapiResponseAdapter.handle (/srv/opendistroforelasticsearch-kibana/src/core/server/http/router/response_adapter.js:81:17)
    at Router.handle (/srv/opendistroforelasticsearch-kibana/src/core/server/http/router/router.js:164:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**This issue is submitted by @Artain**
https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/327

**Comment by ostigley** [comment]
@zhongnansu thanks for merging PR #361. What is the release schedule looking like? I'm keen to install this update.

**Comment by zhongnansu** [comment]
Hi, the PR you referred to has been merged to our latest rc1 release. Please check it out : )
https://opensearch.org/downloads.html

**Comment by ostigley** [comment]
Thanks @zhongnansu. I'm using docker for my opendistro stack, so I was hoping to have version `1.13.2.?` ready to install in my docker file for this plugin: https://github.com/opendistro-for-elasticsearch/kibana-reports.  1.13.2.0 installs with bugs. 

Thanks again for merging the fix though.  Let me know if i've miss-understood. Anything.

**Comment by zhongnansu** [comment]
> Thanks @zhongnansu. I'm using docker for my opendistro stack, so I was hoping to have version `1.13.2.?` ready to install in my docker file for this plugin: https://github.com/opendistro-for-elasticsearch/kibana-reports. 1.13.2.0 installs with bugs.
> 
> Thanks again for merging the fix though. Let me know if i've miss-understood anything.

Currently there's no plan for any security related patch release on the opendistro stack, since we have migrated to the OpenSearch. I asked the team in this thread https://github.com/opensearch-project/opensearch-plugins/issues/69

You can however build your own artifact since the opendistro codebase is still there.
